def errors(err_code):
    err_dict = {
        0: ('OP_ERR_SUCCESS', '정상처리'),
        -10: ('OP_ERR_FAIL', '실패'),
        -11: ('OP_ERR_COND_NUM', '조건번호없슴'),
        -12: ('OP_ERR_COND_MISMATCH', '조건번호와조건식불일치'),
        -13: ('OP_ERR_COND_TR_EXCESS', '조건검색조회요청초과'),
        -100: ('OP_ERR_USER_INFO', '사용자정보교환실패'),
        -101: ('OP_ERR_SERVER_CONNECT', '서버접속실패'),
        -102: ('OP_ERR_VERSION', '버전처리실패'),
        -103: ('OP_ERR_FIREWALL', '개인방화벽실패'),
        -104: ('OP_ERR_MEM', '메모리보호실패'),
        -105: ('OP_ERR_INPUT', '함수입력값오류'),
        -106: ('OP_ERR_CONNECT_END', '통신연결종료'),
        -107: ('OP_ERR_SECU', '보안모듈오류'),
        -108: ('OP_ERR_AUTH_CERT', '공인인증로그인필요'),
        -200: ('OP_ERR_OVER_QUERY', '시세조회과부하'),
        -201: ('OP_ERR_INIT_FAIL', '전문작성초기화실패'),
        -202: ('OP_ERR_INPUT_1', '전문작성입력값오류'),
        -203: ('OP_ERR_NO_DATA', '데이터없음'),
        -204: ('OP_ERR_OVER_TYPE', '조회가능한종목수초과'),
        -205: ('OP_ERR_RECEIVE_FAIL', '데이터수신실패'),
        -206: ('OP_ERR_OVER_FID', '조회가능한FID수초과'),
        -207: ('OP_ERR_RELEASE', '실시간해제오류'),
        -209: ('OP_ERR_LIMIT_QUERY', '시세조회제한'),
        -300: ('OP_ERR_INPUT_2', '입력값오류'),
        -301: ('OP_ERR_PASSWORD', '계좌비밀번호없음'),
        -302: ('OP_ERR_OTHER_ACC', '타인계좌사용오류'),
        -303: ('OP_ERR_ORDER_0', '주문가격이주문착오금액기준초과'),
        -304: ('OP_ERR_ORDER_1', '주문가격이주문착오금액기준초과'),
        -305: ('OP_ERR_ORDER_2', '주문수량이총발행주수의1%초과오류'),
        -306: ('OP_ERR_ORDER_3', '주문수량은총발행주수의3%초과오류'),
        -307: ('OP_ERR_ORDER_TR', '주문전송실패'),
        -308: ('OP_ERR_ORDER_OVERLOAD', '주문전송과부하'),
        -309: ('OP_ERR_ORDERS_EXCEED_300', '주문수량300계약초과'),
        -310: ('OP_ERR_ORDERS_EXCEED_500', '주문수량500계약초과'),
        -311: ('OP_ERR_ORDER_TR_OVCERLOAD', '주문전송제한과부하'),
        -340: ('OP_ERR_NO_ACC', '계좌정보없음'),
        -500: ('OP_ERR_NO_CODE', '종목코드없음')
        }

    return err_dict[err_code]
